# Here's how to run the unit tests with Docker
# docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

services:
  app-tests:
    build:
      context: .
      dockerfile: Dockerfile # test using prod build
    environment:
      - PYTHONPATH=/app
      - RUN_TESTS=True
    volumes:
      - .:/app
      - sqlite-test-data:/app/stats-data/stats-test.db
    command: pytest

volumes:
  sqlite-test-data: